FROM mcr.microsoft.com/devcontainers/typescript-node:24@sha256:cba90c28e53ac2f5a8a5a0388b71b8e98bbe1a4711e0faaa6ef48b137037d4ae

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install gnupg2
